"""Everything doc"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/92_anydoc.ipynb.

# %% ../nbs/92_anydoc.ipynb 1
from __future__ import annotations

# %% auto 0
__all__ = []

# %% ../nbs/92_anydoc.ipynb
#| export


# %% ../nbs/92_anydoc.ipynb
#| export

