"""Real time [nbdev](https://nbdev.fast.ai/)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/95_nbdev_rt.ipynb.

# %% ../nbs/95_nbdev_rt.ipynb 1
from __future__ import annotations


# %% auto 0
__all__ = []

# %% ../nbs/95_nbdev_rt.ipynb
#| export


# %% ../nbs/95_nbdev_rt.ipynb
from .nb_state import NBState

