"""Notebooks as prompts."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/93_prompt.ipynb.

# %% ../nbs/93_prompt.ipynb 1
from __future__ import annotations


# %% auto 0
__all__ = ['prompt', 'Prompt']

# %% ../nbs/93_prompt.ipynb
import inspect
from pathlib import Path
from typing import Literal
from typing import TypeAlias

import anywidget
import traitlets as T
from IPython.display import display
from IPython.display import HTML
from pote.common import update_


# %% ../nbs/93_prompt.ipynb
import bridget


# %% ../nbs/93_prompt.ipynb
class Prompt:
    @staticmethod
    def export(*args, **kwargs):
        pass

prompt = Prompt()
