"""FashHTML widgets"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/50_widget.ipynb.

# %% ../nbs/50_widget.ipynb 1
from __future__ import annotations

# %% auto 0
__all__ = []

# %% ../nbs/50_widget.ipynb
import dataclasses
import typing
from contextlib import contextmanager
from dataclasses import dataclass
from dataclasses import field
from dataclasses import KW_ONLY
from functools import cached_property
from functools import partial
from types import MethodType
from typing import Any
from typing import Callable
from typing import ClassVar
from typing import Iterable
from typing import Sequence
from typing import Type

import psygnal
import traitlets as T
from fastcore.xml import FT
from fastcore.xml import to_xml
from fasthtml.core import FastHTML
from olio.common import val_at
from psygnal import Signal


# %% ../nbs/50_widget.ipynb
from .bridge_plugins import NBHooksPlugin
from .bridget import Bridgeable
from .common import *
from .helpers import id_gen
from .nb_state import NBStateFeedback
from .routing import APIRouterD


# %% ../nbs/50_widget.ipynb
import fasthtml.components as H
from fasthtml.components import Div, Label, Input, Text, I, Select, Option, Span, show


# %% ../nbs/50_widget.ipynb
_n = '\n'
